def resp(author, message):
    respuestas = [
            f'Se dice por ahi que:\n**{message}**',
            f'Algún careverga de por ahí les manda a decir que:\n**{message}**',
            f'Los lideres de oposición comentan que:\n**{message}**',
            f'El que se comió un payaso tiene un comentario:\n**{message}**',
            f'Su cucha le manda a decir que:\n**{message}**',
            f'Diomedes le manda desde la tumba:\n**{message}**',
            f'Oye! Te hablo desde la prisión Wilson Manyoma:\n**{message}**',
            f'El Señor Tenebroso ha enviado un comunicado. Atentos todos:\n**{message}**',
            f'Zoocucha manifiesta que:\n**{message}**',
            f'Extra! Se ha encontrado un fragmento perdido del manifiesto comunista que dice:\n**{message}**',
            message,
            f'Se escucha por las calles del centro que:\n**{message}**',
            f'La nueva cancion de Jbalvin dice:\n**{message}**',
            f'La Pulla subió un video diciendo que:\n**{message}**',
            f'Oigan a mi tia. Disque:\n**{message}**',
            f'He de decir que:\n**{message}**',
            f'Me dijo un pajarito que: \n**{message}**',
            f'Yo lo quiero mucho, pero: \n**{message}**',
            f'Uy la liendra publico en twitter que: \n**{message}**',
            f'No me incumbe pero: \n**{message}**',
            f'Mucha perra, disque: \n**{message}**',
            f'El foro de Sao Paulo ha pronunciado que: \n**{message}**',
            f'La primera linea comenta que: \n**{message}**',
            f'En el congreso me dijeron que: \n**{message}**',
            f'Semana publicó: \n**{message}**',
            f'Jhay cortez me contó que: \n**{message}**',
            f'La fiscalía confirmó que: \n**{message}**',
            f'Un grafiti en la septima dice que: \n**{message}**',
            f'Maria Fernanda Cabal me contó que <@396305256377614337> dijo: \n**{message}**',
            f'Wikileaks ha filtrado un mensaje:\n**{message}**\n Y por culpa de Petro su autor ha quedado al descubierto, {author}'
        ]
    return respuestas